server:
  port: 8081

spring:
  datasource:
    username: root
    password: gcrj_2019_P
    url: jdbc:mysql://localhost:3306/pdf?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.dx340.fileinterconnectionweb.bean

manage:

